name: Crypto application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Docker Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "kraiembechir" --password-stdin
        docker image build -t kraiembechir/DockerGithubActions:latest .  
        docker push kraiembechir/DockerGithubActions:latest
      # add DOCKERPW to Github actions secret